version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - ./rabbitmq-isolated.conf:/etc/rabbitmq/rabbitmq.config
    networks: 
      - backend
  api:
    build: ./Microservice.API
    ports:
      - "5001:5001"
    networks:
      - backend
    environment:
      - CreateTodoCommandQueue=CreateTodo.Command
  eventconsumer:
    build: ./Microservice.EventConsumer
    depends_on: 
      - rabbitmq
    networks: 
      - backend
    environment:
      - CreateTodoCommandQueue=CreateTodo.Command
  datastore:
    build: ./Microservice.Datastore
    ports:
      - "5003:5003"
    networks: 
      - backend

networks:
  backend: